[colors.bright]
black = "#cfc1ba"
blue = "#1d5573"
cyan = "#2b747c"
green = "#3f5a22"
magenta = "#7b3b70"
red = "#94253e"
white = "#4f5e68"
yellow = "#803d1c"

[colors.cursor]
cursor = "#2c363c"
text = "#f0edec"

[colors.normal]
black = "#f0edec"
blue = "#286486"
cyan = "#3b8992"
green = "#4f6c31"
magenta = "#88507d"
red = "#a8334c"
white = "#2c363c"
yellow = "#944927"

[colors.primary]
background = "#f0edec"
foreground = "#2c363c"

[font]
size = 10

[font.bold]
family = "BerkeleyMono Nerd Font"
style = "Bold"

[font.italic]
family = "BerkeleyMono Nerd Font"
style = "Italic"

[font.normal]
family = "BerkeleyMono Nerd Font"
style = "Regular"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[keyboard]
bindings = [
  { chars = "\u0001j", key = "J", mods = "Alt" },
  { chars = "\u0001k", key = "K", mods = "Alt" },
  { chars = "\u0001z", key = "Z", mods = "Alt" },
  { chars = "\u00011", key = "Key1", mods = "Alt" },
  { chars = "\u00012", key = "Key2", mods = "Alt" },
  { chars = "\u00013", key = "Key3", mods = "Alt" },
  { chars = "\u00014", key = "Key4", mods = "Alt" },
  { chars = "\u00015", key = "Key5", mods = "Alt" },
  { chars = "\u00016", key = "Key6", mods = "Alt" },
  { chars = "\u00017", key = "Key7", mods = "Alt" },
  { chars = "\u00018", key = "Key8", mods = "Alt" },
  { chars = "\u00019", key = "Key9", mods = "Alt" },
  { chars = "\u0001s", key = "S", mods = "Alt" },
  { chars = "\u0001[", key = "X", mods = "Control|Shift" },
  { chars = "\u0001p", key = "LBracket", mods = "Alt" },
  { chars = "\u0001n", key = "RBracket", mods = "Alt" },
  { action = "ToggleViMode", key = "Q", mode = "Vi|~Search" },
  { action = "ScrollToBottom", key = "Q", mode = "Vi|~Search" },
]

[selection]
semantic_escape_chars = "/,│`|:\"' ()[]{}<>\t"

[window]
decorations = "none"
dynamic_padding = true
startup_mode = "Windowed"

[window.dimensions]
columns = 120
lines = 30

[window.padding]
x = 5
