[colors.primary]
background = "#14161b"
foreground = "#E0E2EA"
dim_foreground = "#C4C6CD"
bright_foreground = "#E0E2EA"

[colors.cursor]
text = "#14161b"
cursor = "#E0E2EA"

[colors.vi_mode_cursor]
text = "#14161b"
cursor = "#E0E2EA"

[colors.search.matches]
foreground = "#14161b"
background = "#4f5258"

[colors.search.focused_match]
foreground = "#14161b"
background = "#7EDFDE"

[colors.footer_bar]
foreground = "#14161b"
background = "#7EDFDE"

[colors.hints.start]
foreground = "#14161b"
background = "#E5ADB9"

[colors.hints.end]
foreground = "#14161b"
background = "#7EDFDE"

[colors.selection]
text = "#E0E2EA"
background = "#4f5258"

[colors.normal]
black = "#2c2e33"
red = "#E5ADB9"
green = "#A2DFC0"
yellow = "#E3CA85"
blue = "#95C5E5"
magenta = "#E5B6E6"
cyan = "#7EDFDE"
white = "#C4C6CD"

[colors.bright]
black = "#4f5258"
red = "#FFC0B9"
green = "#B4F6C0"
yellow = "#FCE094"
blue = "#A6DBFF"
magenta = "#FFCAFF"
cyan = "#8CF8F7"
white = "#9b9ea4"

[colors.dim]
black = "#2c2e33"
red = "#E5ADB9"
green = "#A2DFC0"
yellow = "#E3CA85"
blue = "#95C5E5"
magenta = "#E5B6E6"
cyan = "#7EDFDE"
white = "#C4C6CD"

[[colors.indexed_colors]]
index = 16
color = "#7EDFDE"

[[colors.indexed_colors]]
index = 17
color = "#4f5258"

[font]
size = 12

[font.normal]
family = "BerkeleyMono Nerd Font"
style = "Regular"

[[hints.enabled]]
command = "open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[keyboard]
bindings = [
  { chars = "\u0001j", key = "J", mods = "Command" },
  { chars = "\u0001k", key = "K", mods = "Command" },
  { chars = "\u0001z", key = "Z", mods = "Command" },
  { chars = "\u00011", key = "Key1", mods = "Command" },
  { chars = "\u00012", key = "Key2", mods = "Command" },
  { chars = "\u00013", key = "Key3", mods = "Command" },
  { chars = "\u00014", key = "Key4", mods = "Command" },
  { chars = "\u00015", key = "Key5", mods = "Command" },
  { chars = "\u00016", key = "Key6", mods = "Command" },
  { chars = "\u00017", key = "Key7", mods = "Command" },
  { chars = "\u00018", key = "Key8", mods = "Command" },
  { chars = "\u00019", key = "Key9", mods = "Command" },
  { chars = "\u0001s", key = "S", mods = "Command" },
  { chars = "\u0001[", key = "X", mods = "Control|Shift" },
  { chars = "\u0001p", key = "LBracket", mods = "Command" },
  { chars = "\u0001n", key = "RBracket", mods = "Command" },
  { action = "ToggleViMode", key = "Q", mode = "Vi|~Search" },
  { action = "ScrollToBottom", key = "Q", mode = "Vi|~Search" },
]

[selection]
semantic_escape_chars = "/,│`|:\"' ()[]{}<>\t"

[window]
decorations = "none"
dynamic_padding = true
option_as_alt = "Both"

[window.dimensions]
columns = 150
lines = 40

[window.padding]
x = 5
