theme = "everforest_dark"

[editor]
line-number = "relative"
cursorline = true
idle-timeout = 0
completion-trigger-len = 1

[editor.cursor-shape]
insert = "bar"

[keys.insert]
j = { k = "normal_mode" }
