[[language]]
name = "lua"
auto-format = true

[[language]]
name = "java"
language-server = { command = "jdt-language-server", args = [
  "-data",
  "/Users/hongjie.yan/.cache/jdtls/workspace/java-play",
] }
roots = ["gradlew", "pom.xml"]

[[language]]
name = "toml"
auto-format = true
